name: Run Quick Tests

on:
  pull_request:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
        mysql:
          image: mysql:8.0.36
          env:
            DB_USER: uo4knvxo5mpdoi1g
            MYSQL_ROOT_PASSWORD: s9cF103Gguk3aGMobBnX
            MYSQL_DATABASE: bumpso1olabrdxegfmme
          ports:
            - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11

      - name: Install Dependencies
        run: npm ci

      - name: Run 1-3 unit tests
        run: npm run test_pr
        env:
            NODE_ENV: test
            DB_HOST: bumpso1olabrdxegfmme-mysql.services.clever-cloud.com
            DB_PORT: 3306
            DB_USER: uo4knvxo5mpdoi1g
            DB_PASSWORD: s9cF103Gguk3aGMobBnX
            DB_DATABASE: bumpso1olabrdxegfmme